# Generated by Django 2.1.4 on 2019-01-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generations',
            name='from_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='generations',
            name='to_year',
            field=models.IntegerField(),
        ),
    ]
